# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624667fc4219fdae4658fd3e32e3a3c1c4e24b577ccc9f389a5d0970db9832beba751d823d9aac4fd2122b7146f22b50eb019eadbbfc2c88c7d9b8059eab3f88

test:
  secret_key_base: ab30bf7f7a71b6b6cfa7c3ed1929bf51d7ec37a572c7dd96c05eade1353d5ea01ca378419950df41c8513fb435a2d436a937bc46ad73d39b4cf6eacb18336601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
